apiVersion: v1
name: irsa
version: 1.0.0
description: extendedapi
home: https://github.com/dominodatalab/extendedapi
keywords:
- extendedapi
- autoshutdown
maintainers:
- email: sameer.wadkar@dominodatalab.com
  name: Sameer Wadkar
