apiVersion: apps.dominodatalab.com/v1alpha1
kind: Mutation
metadata:
  name: {{ .Values.env.name }}
  namespace: {{.Values.env.namespace.platform}}
rules:
- labelSelectors:
  - app.kubernetes.io/name in (spark,ray,dask)
  matchBuilds: false
  modifyLabel:
    key: dominodatalab.com/cluster-workload-type
    value: cluster
- labelSelectors:
  - "dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)"
  insertVolumes:
  - name: {{ .Values.env.name }}-ssl-certs
    secret:
      secretName: "{{.Values.env.name}}-certs"
- labelSelectors:
  - "dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)"
  insertVolumeMounts:
    containerSelector:
    - run
    volumeMounts:
    - name: {{ .Values.env.name }}-ssl-certs
      mountPath: /etc/ssl/certs/{{ .Values.env.name }}
      readOnly: true
  modifyEnv:
    containerSelector:
    - run
    env:
    - name: DOMINO_EXTENDED_API_SSL_CERT
      value: /etc/ssl/certs/{{ .Values.env.name }}/tls.crt
