kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.env.name }}"
subjects:
- kind: ServiceAccount
  name: "{{ .Values.env.name }}"
  namespace: {{ .Values.env.namespace.platform }}
roleRef:
  kind: Role
  name: "{{ .Values.env.name }}"
  apiGroup: rbac.authorization.k8s.io
